db/seedData.js
Tables for users and admins have the same columns for now.
=> created tables for users and admins

db/seedData.js
Made some changes from what we had initially written in figma, let me know what you guys think?
=> create table for reviews completed

db/models/products.js
I started creating db adapters for products, but let me know if we will need any more adapters!
=> created database adapters for products

db/models/products.js, db/models/reviews.js
Reviews db adapters made + small fixes on products db adapters. Please review.
=> db adapters for reviews completed + small fixes on products adapters

db/init_db.js, db/seedData.js
Please note that we still need to finish writing DB adapters for our us to actually initialize data. I just wrote the functions. I'm not sure if this is correct, please let me know if there are any errors. thanks :)
=> initialized data for users, products, orders, reviews

db/client.js, db/init_db.js, db/models/orders.js, db/seedData.js, package-lock.json, package.json
=> 9 db initialize data

db/models/reviews.js
Just added a getReviewById to the db
=> added a getReviewById in reviews db

api/reviews.js
Completed Reviews Api, not too confident about it though, not quite sure where getReviewsByUser or getReviewsByProducts fits in this file. Please review. Thanks
=> api reviews completed

api/products_orders.js
=> api products orders complete

api/orders.js, db/models/orders.js, db/seedData.js
All functions have been tested to work. TODO comments have been added to requireUser/Admin in the code
=> 19 api orders route

api/orders.js, api/reviews.js, db/models/orders.js, db/models/reviews.js
corrected syntax errors for a few get requests
=> 20 api reviews route

api/products.js, db/models/products.js, db/models/user.js, db/seedData.js
Done
- tested all product api routes in postman with requireUser and requireAdmin - everything is working. 
- updated specific sql queries to be case-insensitive to avoid url issues with product names such as "ZZ Plant" - everything is working. 
- added more product seedData 
Help
- I can't figure out how to un-whitelist req.body on updateUser. When destructuring all columns from req.body, it bugs out. I personally just want to leave it at req.body....
=> 25 api bugfix products

api/users.js, db/models/products.js
- finished "un-whitelisting" api patch request on users by de-structuring columns out of req.body (using the ... spread operator) 
- tested in Postman and it appears to be working properly.
=> 24 api bugfix users

api/products.js, index.js, src/axios-services/index.js, src/components/App.js, src/components/Cart.js, src/components/Order/Cart.js, src/components/Order/CartProducts.js, src/components/Order/SingleCartProduct.js, src/components/ShopAll.js, src/components/index.js, src/style/Cart.css
=> 42 frontend cart

src/components/Admin/EditProduct.js, src/components/Admin/Products.js
idk what happened but i have a bug
=> added navigate on edit product button

src/axios-services/index.js, src/components/Admin/AddProduct.js, src/components/Admin/EditProduct.js, src/components/Admin/Orders.js
finished admin: products dashboard (edit, add, delete buttons working)
=> 44 frontend admin

src/components/App.js, src/components/Navigation.js
Navigates to home page after login and login and register buttons disappear and logout appears after user logins
=> finessed the login and register process

src/components/ShopAll.js, src/style/Collections.css
will do the rest of the product pages tonight
=> styled all plants page

db/models/reviews.js, src/components/MyAccount/EditMyAccount.js, src/components/ReviewsByProduct.js
rendered reviews by "username" instead of "id" on product pages
=> 41 frontend product page

package-lock.json, package.json, src/components/Admin/Reviews.js, src/components/MyAccount/MyOrders.js, src/components/MyAccount/MyReviews.js, src/components/MyRating.js, src/components/ReviewForm.js, src/components/ReviewsByProduct.js, src/style/ReviewForm.css
rendered stars on posted reviews. i will work on the stars for posting a review tomorrow
=> 50 frontend bugfix

src/components/App.js, src/components/Navigation.js, src/components/Order/Success.js, src/style/Navigation.css
=> 42 frontend cart icon
